locais = ["China", "Japão", "India", "Russia"]
print(locais)
print(sorted(locais))
print(locais)
print(sorted(locais, reverse=True))
locais.reverse()
print(locais)
locais.reverse()
print(locais)
locais.sort()
print(locais)
locais.sort(reverse=True)
print(locais)
